### ISSUE TITLE
grml-resolution no longer working as expected

### ISSUE THREAD

**Issue by mika** [grml/grml-scripts#14]
The `grml-resolution` script fails to properly parse `xrandr` as it's present nowadays™. We should discuss, whether it's still worth having our own xrandr wrapper, or whether we should switch to something like `arandr` (which would add ~3.5MB of disk space).

**Comment by mika** [comment]
Briefly looked into possible alternatives:

* autorandr: ~113kb(!)
* arandr: ~4043kb
* lxrandr: ~27MB (so clearly not an option)

Given that `autorandr common` seems to also work e.g. in VirtualBox to maximize resolution, arandr works nicely (and has somewhat working disk space requiements), and also `unxrandr` provides an output that might be useful to use in `xrandr` (with custom option), I'd suggest we drop our `grml-resolution`  script and decide which tools to actually ship.

Opinions?

**Comment by jkirk** [comment]
Also did quick look:  `xrandr` is provided by `x11-xserver-utils`. Are you planning to remove the package (which would free only about 1MB)? If not, I would avoid installing another package just to change the resolution.

That said, `autorandr common` did not work so fine for me. My display (in VirtualBox) got black, I had to kill the X-Server.

The GUI of `arandr` looks nice (kind of 😉 ) but pulls in some stuff.

Also looked in `grml-resolution`. A fix does not seem too hard... (I think I could provide a quick fix for it.)

**Comment by jkirk** [comment]
Sigh, it seems like the `grml-resolution` did not work 'as expected' since quite a while now:
 
![screenshot_20221127T131520](https://user-images.githubusercontent.com/288637/204136923-760588a7-b915-4092-b506-94bff864ddd6.png)

grml-resolution in PR grml/grml-scripts#16 now looks like this:

![screenshot_20221127T133139](https://user-images.githubusercontent.com/288637/204137098-4e11976f-f9d2-4e90-a14b-26681f6c8a3f.png)
